name: built_value_absent
description: A simple repo to test absent vs null in built_value.
version: 1.0.0

environment:
  sdk: '>=2.16.0 <3.0.0'


dependencies:
  built_value: ^8.0.0

dev_dependencies:
  build_runner: ^2.1.9
  built_value_generator: ^8.2.0
  lints: ^1.0.0
